# Generated by Django 5.2.7 on 2026-09-05 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLink',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('devise', models.CharField(default='XAF', max_length=10)),
                ('langue', models.CharField(default='fr', max_length=5)),
                ('description', models.TextField(blank=True, null=True)),
                ('canal_envoi', models.CharField(blank=True, choices=[('mail', 'Mail'), ('sms', 'SMS')], max_length=10, null=True)),
                ('moyen_paiement', models.CharField(blank=True, choices=[('mtn', 'MTN'), ('orange', 'Orange'), ('carte', 'Carte'), ('autre', 'Autre')], max_length=15, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('expired', 'Expired'), ('failed', 'Failed')], default='pending', max_length=15)),
                ('soleaspay_ref', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.PROTECT, related_name='payment_links', to='core.client')),
                ('order', models.ForeignKey(blank=True, db_column='order_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_links', to='core.order')),
            ],
            options={
                'db_table': 'payment_links',
            },
        ),
    ]
