# Generated by Django 5.2.7 on 2026-09-05 21:39

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_id', models.CharField(max_length=64, unique=True)),
                ('pickup_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('destination_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('proposed_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=30)),
                ('fetched_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'demand_cache',
            },
        ),
        migrations.CreateModel(
            name='OptimizationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_snapshot', models.JSONField()),
                ('output_turn', models.JSONField()),
                ('expected_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(db_column='driver_id', on_delete=django.db.models.deletion.CASCADE, related_name='optimization_runs', to='accounts.user')),
            ],
            options={
                'db_table': 'optimization_runs',
            },
        ),
    ]
