# Generated by Django 5.2.7 on 2026-09-05 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=150, null=True)),
                ('contact_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=191)),
                ('phone', models.CharField(max_length=30)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(default='Douala', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_profile', to='accounts.user')),
            ],
            options={
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPTIMIZED', 'Optimized'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('optimized_geometry', models.JSONField(blank=True, null=True)),
                ('total_distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('estimated_duration_min', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(db_column='driver_id', on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='accounts.user')),
            ],
            options={
                'db_table': 'routes',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=64, unique=True)),
                ('delivery_address', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('IN_TRANSIT', 'In transit'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('amount_to_collect', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.client')),
                ('route', models.ForeignKey(blank=True, db_column='route_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.route')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('registration_number', models.CharField(max_length=30, unique=True)),
                ('model', models.CharField(max_length=100)),
                ('capacity_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('volume_m3', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('IN_TRANSIT', 'In transit'), ('MAINTENANCE', 'Maintenance')], default='AVAILABLE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_driver', models.OneToOneField(blank=True, db_column='assigned_driver_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vehicle', to='accounts.user')),
            ],
            options={
                'db_table': 'vehicles',
            },
        ),
        migrations.AddField(
            model_name='route',
            name='vehicle',
            field=models.ForeignKey(db_column='vehicle_id', on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='core.vehicle'),
        ),
    ]
