# Generated by Django 5.2.7 on 2026-09-05 21:39

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.contrib.postgres.operations import CreateExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        CreateExtension('postgis'),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('boundary', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'zones',
            },
        ),
        migrations.CreateModel(
            name='DriverTrajectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('tolerance_meters', models.PositiveIntegerField(default=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(db_column='driver_id', on_delete=django.db.models.deletion.CASCADE, related_name='trajectories', to='accounts.user')),
            ],
            options={
                'db_table': 'driver_trajectories',
            },
        ),
        migrations.CreateModel(
            name='Carrefour',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('is_pickup_point', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zone', models.ForeignKey(blank=True, db_column='zone_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carrefours', to='geolocation.zone')),
            ],
            options={
                'db_table': 'carrefours',
            },
        ),
        migrations.CreateModel(
            name='DriverLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('speed', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('heading', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('recorded_at', models.DateTimeField()),
                ('driver', models.ForeignKey(db_column='driver_id', on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='accounts.user')),
            ],
            options={
                'db_table': 'driver_locations',
                'indexes': [models.Index(fields=['driver', '-recorded_at'], name='driver_loca_driver__a7d95d_idx')],
            },
        ),
        migrations.CreateModel(
            name='CongestionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('congestion_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('recorded_at', models.DateTimeField()),
                ('zone', models.ForeignKey(db_column='zone_id', on_delete=django.db.models.deletion.CASCADE, related_name='congestion_snapshots', to='geolocation.zone')),
            ],
            options={
                'db_table': 'congestion_snapshots',
                'indexes': [models.Index(fields=['zone', '-recorded_at'], name='congestion__zone_id_1410d4_idx')],
            },
        ),
    ]
