# Generated by Django 5.2.7 on 2026-09-07 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorridorLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=10, unique=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('city', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('start_point', models.CharField(max_length=150)),
                ('end_point', models.CharField(max_length=150)),
                ('stops', models.JSONField(default=list)),
                ('standard_fare_fcfa', models.PositiveIntegerField(default=400)),
                ('distance_km', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('estimated_duration_min', models.PositiveSmallIntegerField(default=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'corridor_lines',
            },
        ),
        migrations.AddField(
            model_name='carrefour',
            name='city',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='carrefour',
            name='is_major_intersection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carrefour',
            name='standard_fare_to_centre_fcfa',
            field=models.PositiveIntegerField(default=400),
        ),
        migrations.AddField(
            model_name='carrefour',
            name='typical_waiting_passengers',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='zone',
            name='city',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
