# Generated by Django 5.2.7 on 2026-09-07 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corridor_axis', models.CharField(blank=True, default='', max_length=255)),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('total_rides', models.PositiveIntegerField(default=0)),
                ('wallet_balance_fcfa', models.PositiveIntegerField(default=0)),
                ('is_online', models.BooleanField(default=False)),
                ('current_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('current_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('active_corridor', models.CharField(blank=True, default='', max_length=255)),
                ('cabin_seats', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='accounts.user')),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
    ]
