# Generated by Django 5.2.7 on 2026-09-07 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ride_id', models.CharField(max_length=32, unique=True)),
                ('status', models.CharField(choices=[('searching', 'Searching'), ('matched', 'Matched'), ('en_route', 'En route'), ('in_trip', 'In trip'), ('completed', 'Completed')], default='searching', max_length=20)),
                ('pickup_carrefour_id', models.IntegerField()),
                ('pickup_name', models.CharField(max_length=150)),
                ('destination_carrefour_id', models.IntegerField()),
                ('destination_name', models.CharField(max_length=150)),
                ('ride_type', models.CharField(default='shared', max_length=20)),
                ('seats_count', models.PositiveSmallIntegerField(default=1)),
                ('payment_method', models.CharField(default='cash', max_length=20)),
                ('passenger_notes', models.TextField(blank=True, default='')),
                ('fare_fcfa', models.PositiveIntegerField(default=500)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rating_comment', models.TextField(blank=True, default='')),
                ('tip_fcfa', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, db_column='driver_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rides_as_driver', to='accounts.user')),
                ('passenger', models.ForeignKey(db_column='passenger_id', on_delete=django.db.models.deletion.CASCADE, related_name='rides_as_passenger', to='accounts.user')),
            ],
            options={
                'db_table': 'rides',
            },
        ),
    ]
